### ISSUE TITLE
Stock rom or Custom Rom

### ISSUE THREAD

**Issue by IamCOD3X** [khaeruirgi/kernel_xiaomi_camellia#1]
Is it for stock ROM or Custom ROM, also what's the supported Android Version

**Comment by khaeruirgi** [comment]
Stock rom miui 12 Android 11, It's camellia-r-oss based, there's no r vendor based custom rom and all custom rom used Prebuilt kernel.

**Comment by IamCOD3X** [comment]
Thanks for reply. Now you can close the issue..! Have a nice day.!

**Comment by IamCOD3X** [comment]
Suggested compiler?

**Comment by khaeruirgi** [comment]
Clang

**Comment by IamCOD3X** [comment]
Any specific clang version? And will it support MIUI 12.x till MIUI 12.0.9.0?

**Comment by khaeruirgi** [comment]
You can use any version of Clang, but I myself use Proton Clang 11, it
works on all Miui 12.

Pada tanggal Sel, 13 Jun 2023 11.57, Sourabh Panchal <
***@***.***> menulis:

**Comment by IamCOD3X** [comment]
Compiled Successfully but not booting up with MIUI Version- 12.5.6

**Comment by khaeruirgi** [comment]
Can you take logs?

**Comment by khaeruirgi** [comment]
I just compiled this kernel from micode camellia-r-oss, then fixed a lot of compile failures, but haven't test boot or not on miui 12.5, you should fix that.

**Comment by IamCOD3X** [comment]
Well I don't own the device.. one of my college friend have that device.. and he's kinda new to this stuff.. but I will try to fix things up.. thanks. 👍
